### ISSUE TITLE
Not working on demo

### ISSUE THREAD

**Issue by ChangJoo-Park** [hodgef/js-library-boilerplate-basic#195]
I use this repo on my mac.  I try to build and demo (with `serve -s demo`). but it is not working.
All code are latest commit. It does not have changes. 

This is error I've met on Chrome.

```
Uncaught SyntaxError: Unexpected token '<'
main.js:1 Uncaught TypeError: Cannot read property 'default' of undefined
    at main.js:1
```

How do I do?

**Comment by hodgef** [comment]
Hello @ChangJoo-Park , did you run `npm run build` before? I can't reproduce your issue on my end. Chrome 85 Win10, also latest commit.

![image](https://user-images.githubusercontent.com/25509135/92851215-4e851580-f3bb-11ea-8414-5f55304aeab2.png)

Regards,
Francisco Hodge

**Comment by ChangJoo-Park** [comment]
Yes I run build script before demo.
I'll try again. Thanks
