### ISSUE TITLE
E404 when running npm publish

### ISSUE THREAD

**Issue by danielgoodwin97** [hodgef/js-library-boilerplate-basic#206]
I'm getting this error when running `npm publish`.
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT http://registry.npmjs.org/@hodgef%2fjs-library-boilerplate-basic - Not found
npm ERR! 404 
npm ERR! 404  '@hodgef/js-library-boilerplate-basic@1.4.22' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
I'm super clueless with this so I'm hoping I'm just doing something dumb.

**Comment by hodgef** [comment]
Hello @danielgoodwin97 !

Per the [Customization guide](https://github.com/hodgef/js-library-boilerplate-basic#-customization):

>## 💎 Customization
> Before shipping, make sure to:
>1. Edit `LICENSE` file
>2. Edit `package.json` information (These will be used to generate the headers for your built files)
>3. Edit `library: "MyLibrary"` with your library's export name in `./webpack.config.js`

I think in your package.json there's still some stuff pointing to js-library-boilerplate. Make sure to change those to match your desired package name. Thanks!

**Comment by danielgoodwin97** [comment]
That's embarrassing 😅. Thanks!
