### ISSUE TITLE
how to pass in env var from package.json

### ISSUE THREAD

**Issue by jasan-s** [hodgef/js-library-boilerplate-basic#432]
I tried the following unsuccesfully using `dotenv-webpack`
    "start": "set APP_ENV=dev && PORT=3005 webpack serve",

**Comment by hodgef** [comment]
If you're using Windows you can try
```
"set APP_ENV=dev&& set PORT=3005&& webpack serve"
```
![image](https://user-images.githubusercontent.com/25509135/127736445-a6a1cd10-72f5-4935-b792-eddd04752c32.png)

You can probably find various approaches through search, like here:
https://stackoverflow.com/a/55238396/1467941

Regards,
Francisco Hodge
